/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nn.ovchinnikov.lab2.classification;

import nn.ovchinnikov.lab2.classification.ml.*;
import nn.ovchinnikov.lab2.classification.util.VoiceDataReader;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.apache.spark.sql.*;

public class App {

    public static void main(String[] args) throws Exception {
        Logger.getLogger("org").setLevel(Level.OFF);
        Logger.getLogger("akka").setLevel(Level.OFF);

        SparkSession spark = SparkSession
                .builder()
                .appName("Classification App")
                .master("local[*]")
                .getOrCreate();

        System.out.println("Voice Train Data:");
        Dataset<Row> trainingData = VoiceDataReader.readDataset(spark, "datasets/voice-train.csv");
        System.out.println("Voice Test Data:");
        Dataset<Row> testData = VoiceDataReader.readDataset(spark, "datasets/voice-test.csv");

        BaggingLogisticRegressionML.build(trainingData, testData);
        BaggingDecisionTreeML.build(trainingData, testData);
        BaggingSVMML.build(trainingData, testData);
        DecisionTreeML.build(trainingData, testData);
        GradientBoostedTreeML.build(trainingData, testData);
        LinearSVCML.build(trainingData, testData);
        LogisticRegressionML.build(trainingData, testData);
        RandomForestML.build(trainingData, testData);
        StackingML.build(trainingData, testData);

        spark.stop();
    }
}
