/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package nn.ovchinnikov.lab2.classification;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testApp() {
    }
}
